HPC<-read.table("household_power_consumption.txt",sep=";",header = T, na.strings = "?")
HPC$Date <- as.Date(HPC$Date, format = "%d/%m/%Y")
HPC<-subset(HPC, HPC$Date == "2007-02-01"| HPC$Date =="2007-02-02")
HPC$DateTime <- strptime(paste(HPC$Date, HPC$Time), "%Y-%m-%d %H:%M:%S")
hist(HPC$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.copy(png, file = "plot1.png", height = 480, width = 480)
dev.off()